services:
  postgres:
    image: postgres:16
    container_name: lernia-db
    restart: always
    environment:
      POSTGRES_USER: lernia
      POSTGRES_PASSWORD: lernia
      POSTGRES_DB: lernia
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lernia-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: lernia-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lernia.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - lernia-network
    depends_on:
      - postgres

networks:
  lernia-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
