services:
  postgres:
    image: postgres:16
    container_name: lernia-db
    restart: always
    environment:
      POSTGRES_USER: lernia
      POSTGRES_PASSWORD: lernia
      POSTGRES_DB: lernia
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
